abstract class AppStrings {
  static const String appName = "Postly";
  static const String appTagline = "Build your LinkedIn brand on autopilot";
  static const String signInWithLinkedIn = "Continue with LinkedIn";
  static const String continueAsGuest = "Preview Demo";
  static const String termsOfService = "Terms of Service";
  static const String privacyPolicy = "Privacy Policy";
  static const String footerSeparator = " · ";
  static const String featureOneTitle = "Daily AI Drafts";
  static const String featureOneSubtitle =
      "Fresh posts generated every morning";
  static const String featureTwoTitle = "One-Tap Publish";
  static const String featureTwoSubtitle =
      "Review, edit, and post to LinkedIn instantly";
  static const String featureThreeTitle = "Smart Autopilot";
  static const String featureThreeSubtitle =
      "Customise tone, topics & schedule";

  static const String termsContent = '''
Last updated: July 2026

1. Acceptance of Terms
By accessing or using PostTech AI ("the App"), you agree to be bound by these Terms of Service. If you do not agree, please do not use the App.

2. Description of Service
PostTech AI is an AI-powered tool that fetches tech news, generates LinkedIn post drafts, and allows you to review and publish content to LinkedIn via OAuth. The App acts as a content assistant and does not guarantee any specific results from published posts.

3. LinkedIn Integration
When you connect your LinkedIn account, you authorise PostTech AI to post content on your behalf only when you explicitly tap "Publish". We do not store your LinkedIn credentials. Access tokens are securely handled and can be revoked at any time from your LinkedIn account settings.

4. User Responsibilities
You are solely responsible for all content you choose to publish. You agree not to use the App to publish misleading, defamatory, or unlawful content. You must comply with LinkedIn's own Terms of Service.

5. AI-Generated Content
Content generated by the App is produced by AI and may contain inaccuracies. Always review drafts before publishing. PostTech AI is not liable for any consequences arising from published content.

6. Intellectual Property
The App and its original content, features, and functionality are owned by PostTech AI and are protected by applicable intellectual property laws.

7. Termination
We reserve the right to suspend or terminate your access at any time for violation of these Terms.

8. Limitation of Liability
PostTech AI is provided "as is" without warranties of any kind. We are not liable for indirect, incidental, or consequential damages arising from your use of the App.

9. Changes to Terms
We may update these Terms at any time. Continued use of the App after changes constitutes acceptance of the new Terms.

10. Contact
For any questions regarding these Terms, contact us at support@posttechai.app
''';

  static const String privacyContent = '''
Last updated: July 2026

1. Information We Collect
• Account Data: When you sign in with LinkedIn, we receive your public profile information (name, profile picture, headline) via LinkedIn OAuth.
• Usage Data: We collect anonymised data about how you interact with the App (screens visited, features used) to improve our service.
• Device Data: Basic device information (OS version, device type) for debugging purposes.

2. Information We Do Not Collect
We do not collect or store your LinkedIn password. We do not sell, trade, or rent your personal information to third parties.

3. How We Use Your Information
• To generate personalised AI content drafts based on your preferences.
• To publish content to LinkedIn on your explicit instruction.
• To send push notifications about new drafts (only if you opt in).
• To improve the App's features and performance.

4. Data Storage & Security
Your data is stored securely using industry-standard encryption. LinkedIn access tokens are stored in your device's secure storage and are never transmitted to our servers in plain text.

5. Third-Party Services
The App uses the following third-party services:
• LinkedIn API — for authentication and publishing
• OpenAI API — for AI content generation
• Firebase — for push notifications and analytics

Each service has its own privacy policy which we encourage you to review.

6. Your Rights
You have the right to access, correct, or delete your personal data at any time. To request data deletion, contact us at privacy@posttechai.app or disconnect the App from your LinkedIn account settings.

7. Children's Privacy
The App is not directed at individuals under the age of 16. We do not knowingly collect personal data from children.

8. Changes to This Policy
We may update this Privacy Policy periodically. We will notify you of significant changes via the App or email.

9. Contact
For privacy-related questions, contact us at privacy@posttechai.app
''';
}
